using AutoFixture.Xunit2;

namespace Nimator.Couchbase.Tests
{
    /// <inheritdoc />
    /// <summary>
    /// When placed on a test method, this attribute will cause method parameters to be automatically generated by AutoFixture as configured in <see cref="!:CouchBaseFixture" />.
    /// </summary>
    public class CouchBaseFixtureAttribute : AutoDataAttribute
    {
        public CouchBaseFixtureAttribute() : base(() => new CouchBaseFixture())
        {
        }
    }
}
